### ISSUE TITLE
Non-monotonicity in `survivorship` for fractional years

### ISSUE THREAD

**Issue by nilshg** [JuliaActuary/MortalityTables.jl#60]
This seems slightly odd and like a bug:

```
using MortalityTables, Plots

tables = MortalityTables.tables()
tab_now = tables["2001 CSO Preferred Select and Ultimate - Female Nonsmoker, ALB"]

p = plot()
for a ∈ 95:0.6:98
    plot!(p, [survivorship(tab_now.ultimate, a, x, MortalityTables.Balducci()) 
        for x ∈ a:0.1:120], label = "$a", xlim = (0,24), xlabel = "Months", 
            ylabel = "Survivorship")
end
p
```
Produces:
![image](https://user-images.githubusercontent.com/7264491/84787196-99260a00-afe5-11ea-8779-12c6cbcdb754.png)

I've confirmed that this problem exists for different ages, different mortality tables, and all methods of splitting up the year (`Uniform`, `Constant`, and `Balducci`).

Is this a bug or am I doing something I shouldn't be doing?

**Comment by alecloudenback** [comment]
Thank you for the report! It was indeed a bug when the starting age was not an integer age and the period of time for survivorship didn't reach the next integral age. This is fixed in #62 and is in the process of being tagged as `v0.9.2` and merged into the General Registry.

Very clever way to index the remaining ages, btw - creating a range of attained ages from the start to the ultimate age. One suggestion is that since you are incrementing by 1/10 of a year instead of 1/12, I think you might want `x ∈ a:(1/12):120` in order to match with your x lims.
